// This file was auto-generated by graphql-fragment-codegen. Do not edit it by hand.

export const ListResult = `fragment ListResult on ListResult {
  pagination {
    total
    size
    pageCount
    currentPage
  }
}
`;

export const Crag = `fragment Crag on Crag {
  _stats {
    routesCount
    sectorsCount
  }
  slug
  title
  descr
  access_info
  coords {
    lat
    lng
  }
  altitude
  exposition
  bolding_type
  rock_type
  quality_rank {
    score
    crowdedness
    weather
    weatherExtended {
    coeff
    time
    value
  }
    position
    difficulty
    average
    max
    votes
  }
  period
  notes
  resource_url
  sectors {
    crag
    parent {
      _stats {
        routesCount
        sectorsCount
      }
      slug
      title
      descr
      access_info
      coords {
        lat
        lng
      }
      altitude
      exposition
      bolding_type
      rock_type
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      period
      notes
      resource_url
    }
    slug
    title
    coords {
      lat
      lng
    }
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    min_grade
    max_grade
    resource_url
    routes {
    sector
    parent {
      crag
      parent {
        _stats {
          routesCount
          sectorsCount
        }
        slug
        title
        descr
        access_info
        coords {
          lat
          lng
        }
        altitude
        exposition
        bolding_type
        rock_type
        quality_rank {
          score
          crowdedness
          weather
          weatherExtended {
    coeff
    time
    value
  }
          position
          difficulty
          average
          max
          votes
        }
        period
        notes
        resource_url
      }
      slug
      title
      coords {
        lat
        lng
      }
      notes
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      min_grade
      max_grade
      resource_url
    }
    slug
    seq_num
    title
    coords {
      lat
      lng
    }
    grade
    pitons_num
    length
    route_type
    gear_type
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    resource_url
    search_score
  }
    search_score
  }
  search_score
}
`;

export const CragStats = `fragment CragStats on CragStats {
  routesCount
  sectorsCount
}
`;

export const Coords = `fragment Coords on Coords {
  lat
  lng
}
`;

export const QualityRank = `fragment QualityRank on QualityRank {
  score
  crowdedness
  weather
  weatherExtended {
    coeff
    time
    value
  }
  position
  difficulty
  average
  max
  votes
}
`;

export const WeatherExtended = `fragment WeatherExtended on WeatherExtended {
  coeff
  time
  value
}
`;

export const Sector = `fragment Sector on Sector {
  crag
  parent {
    _stats {
      routesCount
      sectorsCount
    }
    slug
    title
    descr
    access_info
    coords {
      lat
      lng
    }
    altitude
    exposition
    bolding_type
    rock_type
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    period
    notes
    resource_url
  }
  slug
  title
  coords {
    lat
    lng
  }
  notes
  quality_rank {
    score
    crowdedness
    weather
    weatherExtended {
    coeff
    time
    value
  }
    position
    difficulty
    average
    max
    votes
  }
  min_grade
  max_grade
  resource_url
  routes {
    sector
    parent {
      crag
      parent {
        _stats {
          routesCount
          sectorsCount
        }
        slug
        title
        descr
        access_info
        coords {
          lat
          lng
        }
        altitude
        exposition
        bolding_type
        rock_type
        quality_rank {
          score
          crowdedness
          weather
          weatherExtended {
    coeff
    time
    value
  }
          position
          difficulty
          average
          max
          votes
        }
        period
        notes
        resource_url
      }
      slug
      title
      coords {
        lat
        lng
      }
      notes
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      min_grade
      max_grade
      resource_url
    }
    slug
    seq_num
    title
    coords {
      lat
      lng
    }
    grade
    pitons_num
    length
    route_type
    gear_type
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    resource_url
    search_score
  }
  search_score
}
`;

export const SectorCrag = `fragment SectorCrag on SectorCrag {
  _stats {
    routesCount
    sectorsCount
  }
  slug
  title
  descr
  access_info
  coords {
    lat
    lng
  }
  altitude
  exposition
  bolding_type
  rock_type
  quality_rank {
    score
    crowdedness
    weather
    weatherExtended {
    coeff
    time
    value
  }
    position
    difficulty
    average
    max
    votes
  }
  period
  notes
  resource_url
}
`;

export const Route = `fragment Route on Route {
  sector
  parent {
    crag
    parent {
      _stats {
        routesCount
        sectorsCount
      }
      slug
      title
      descr
      access_info
      coords {
        lat
        lng
      }
      altitude
      exposition
      bolding_type
      rock_type
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      period
      notes
      resource_url
    }
    slug
    title
    coords {
      lat
      lng
    }
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    min_grade
    max_grade
    resource_url
  }
  slug
  seq_num
  title
  coords {
    lat
    lng
  }
  grade
  pitons_num
  length
  route_type
  gear_type
  notes
  quality_rank {
    score
    crowdedness
    weather
    weatherExtended {
    coeff
    time
    value
  }
    position
    difficulty
    average
    max
    votes
  }
  resource_url
  search_score
}
`;

export const RouteSector = `fragment RouteSector on RouteSector {
  crag
  parent {
    _stats {
      routesCount
      sectorsCount
    }
    slug
    title
    descr
    access_info
    coords {
      lat
      lng
    }
    altitude
    exposition
    bolding_type
    rock_type
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    period
    notes
    resource_url
  }
  slug
  title
  coords {
    lat
    lng
  }
  notes
  quality_rank {
    score
    crowdedness
    weather
    weatherExtended {
    coeff
    time
    value
  }
    position
    difficulty
    average
    max
    votes
  }
  min_grade
  max_grade
  resource_url
}
`;

export const Place = `fragment Place on Place {
  _id
  social_id
  slug
  title
  descr
  coords {
    lat
    lng
  }
  openings {
    l
  }
  notes
  resource_url
  search_score
  picture
}
`;

export const Openings = `fragment Openings on Openings {
  l
}
`;

export const Event = `fragment Event on Event {
  social_id
  slug
  title
  descr
  coords {
    lat
    lng
  }
  place
  start_time
  end_time
  resource_url
  search_score
}
`;

export const Competition = `fragment Competition on Competition {
  coords {
    lat
    lng
  }
  info {
    categories
    details {
      event_website
      info_sheet
      text
    }
    place
    specialties
    types
  }
  people {
    what
    who
  }
  poster
  resource_url
  schedule
  slug
  start_time
  end_time
  title
  search_score
}
`;

export const CompetitionInfo = `fragment CompetitionInfo on CompetitionInfo {
  categories
  details {
    event_website
    info_sheet
    text
  }
  place
  specialties
  types
}
`;

export const CompetitionDetails = `fragment CompetitionDetails on CompetitionDetails {
  event_website
  info_sheet
  text
}
`;

export const CompetitionPerson = `fragment CompetitionPerson on CompetitionPerson {
  what
  who
}
`;

export const News = `fragment News on News {
  media {
    thumb
  }
  resource_url
  slug
  summary
  title
  lang
  search_score
  creation_time
}
`;

export const NewsMedia = `fragment NewsMedia on NewsMedia {
  thumb
}
`;

export const Shelter = `fragment Shelter on Shelter {
  slug
  name
  descr
  coords {
    lat
    lng
  }
  access_info
  altitude
  opening
  accomodations_food
  accomodations_rooms
  beds
  owners
  keepers
  email
  phone
  mobile
  web
  facebook
  media
  search_score
  resource_url
}
`;

export const Hike = `fragment Hike on Hike {
  slug
  title
  trail_label
  difficulty
  exposition
  elevation {
    asc
    desc
    low
    high
    asc_diff_tot
  }
  grade {
    avg
    max
  }
  length
  starting_point
  access_info
  notes
  descr
  coords {
    lat
    lng
  }
  tracks
  media
  search_score
  resource_url
}
`;

export const HikeElevation = `fragment HikeElevation on HikeElevation {
  asc
  desc
  low
  high
  asc_diff_tot
}
`;

export const HikeGrade = `fragment HikeGrade on HikeGrade {
  avg
  max
}
`;

export const Pagination = `fragment Pagination on Pagination {
  total
  size
  pageCount
  currentPage
}
`;

export const UserInfo = `fragment UserInfo on UserInfo {
  geo {
    isoCode
    timeZone
    city
    coords {
      lat
      lng
    }
  }
}
`;

export const UserGeo = `fragment UserGeo on UserGeo {
  isoCode
  timeZone
  city
  coords {
    lat
    lng
  }
}
`;

export const SearchResult = `fragment SearchResult on SearchResult {
  locations {
    name
    coords {
      lat
      lng
    }
  }
  crags {
    _stats {
      routesCount
      sectorsCount
    }
    slug
    title
    descr
    access_info
    coords {
      lat
      lng
    }
    altitude
    exposition
    bolding_type
    rock_type
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    period
    notes
    resource_url
    sectors {
    crag
    parent {
      _stats {
        routesCount
        sectorsCount
      }
      slug
      title
      descr
      access_info
      coords {
        lat
        lng
      }
      altitude
      exposition
      bolding_type
      rock_type
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      period
      notes
      resource_url
    }
    slug
    title
    coords {
      lat
      lng
    }
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    min_grade
    max_grade
    resource_url
    routes {
    sector
    parent {
      crag
      parent {
        _stats {
          routesCount
          sectorsCount
        }
        slug
        title
        descr
        access_info
        coords {
          lat
          lng
        }
        altitude
        exposition
        bolding_type
        rock_type
        quality_rank {
          score
          crowdedness
          weather
          weatherExtended {
    coeff
    time
    value
  }
          position
          difficulty
          average
          max
          votes
        }
        period
        notes
        resource_url
      }
      slug
      title
      coords {
        lat
        lng
      }
      notes
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      min_grade
      max_grade
      resource_url
    }
    slug
    seq_num
    title
    coords {
      lat
      lng
    }
    grade
    pitons_num
    length
    route_type
    gear_type
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    resource_url
    search_score
  }
    search_score
  }
    search_score
  }
  sectors {
    crag
    parent {
      _stats {
        routesCount
        sectorsCount
      }
      slug
      title
      descr
      access_info
      coords {
        lat
        lng
      }
      altitude
      exposition
      bolding_type
      rock_type
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      period
      notes
      resource_url
    }
    slug
    title
    coords {
      lat
      lng
    }
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    min_grade
    max_grade
    resource_url
    routes {
    sector
    parent {
      crag
      parent {
        _stats {
          routesCount
          sectorsCount
        }
        slug
        title
        descr
        access_info
        coords {
          lat
          lng
        }
        altitude
        exposition
        bolding_type
        rock_type
        quality_rank {
          score
          crowdedness
          weather
          weatherExtended {
    coeff
    time
    value
  }
          position
          difficulty
          average
          max
          votes
        }
        period
        notes
        resource_url
      }
      slug
      title
      coords {
        lat
        lng
      }
      notes
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      min_grade
      max_grade
      resource_url
    }
    slug
    seq_num
    title
    coords {
      lat
      lng
    }
    grade
    pitons_num
    length
    route_type
    gear_type
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    resource_url
    search_score
  }
    search_score
  }
  routes {
    sector
    parent {
      crag
      parent {
        _stats {
          routesCount
          sectorsCount
        }
        slug
        title
        descr
        access_info
        coords {
          lat
          lng
        }
        altitude
        exposition
        bolding_type
        rock_type
        quality_rank {
          score
          crowdedness
          weather
          weatherExtended {
    coeff
    time
    value
  }
          position
          difficulty
          average
          max
          votes
        }
        period
        notes
        resource_url
      }
      slug
      title
      coords {
        lat
        lng
      }
      notes
      quality_rank {
        score
        crowdedness
        weather
        weatherExtended {
    coeff
    time
    value
  }
        position
        difficulty
        average
        max
        votes
      }
      min_grade
      max_grade
      resource_url
    }
    slug
    seq_num
    title
    coords {
      lat
      lng
    }
    grade
    pitons_num
    length
    route_type
    gear_type
    notes
    quality_rank {
      score
      crowdedness
      weather
      weatherExtended {
    coeff
    time
    value
  }
      position
      difficulty
      average
      max
      votes
    }
    resource_url
    search_score
  }
  events {
    social_id
    slug
    title
    descr
    coords {
      lat
      lng
    }
    place
    start_time
    end_time
    resource_url
    search_score
  }
  competitions {
    coords {
      lat
      lng
    }
    info {
      categories
      details {
        event_website
        info_sheet
        text
      }
      place
      specialties
      types
    }
    people {
    what
    who
  }
    poster
    resource_url
    schedule
    slug
    start_time
    end_time
    title
    search_score
  }
  news {
    media {
      thumb
    }
    resource_url
    slug
    summary
    title
    lang
    search_score
    creation_time
  }
  places {
    _id
    social_id
    slug
    title
    descr
    coords {
      lat
      lng
    }
    openings {
      l
    }
    notes
    resource_url
    search_score
    picture
  }
  shelters {
    slug
    name
    descr
    coords {
      lat
      lng
    }
    access_info
    altitude
    opening
    accomodations_food
    accomodations_rooms
    beds
    owners
    keepers
    email
    phone
    mobile
    web
    facebook
    media
    search_score
    resource_url
  }
  hikes {
    slug
    title
    trail_label
    difficulty
    exposition
    elevation {
      asc
      desc
      low
      high
      asc_diff_tot
    }
    grade {
      avg
      max
    }
    length
    starting_point
    access_info
    notes
    descr
    coords {
      lat
      lng
    }
    tracks
    media
    search_score
    resource_url
  }
  pagination {
    total
    size
    pageCount
    currentPage
  }
}
`;

export const City = `fragment City on City {
  name
  coords {
    lat
    lng
  }
}
`;

export const ForecastResult = `fragment ForecastResult on ForecastResult {
  now {
    time
    summary
    icon
    nearestStormDistance
    nearestStormBearing
    precipIntensity
    precipProbability
    temperature
    apparentTemperature
    dewPoint
    humidity
    pressure
    windSpeed
    windGust
    windBearing
    cloudCover
    uvIndex
    visibility
    ozone
  }
  forecast {
    time
    summary
    icon
    sunriseTime
    sunsetTime
    moonPhase
    precipIntensity
    precipIntensityMax
    precipIntensityMaxTime
    precipProbability
    precipType
    temperatureHigh
    temperatureHighTime
    temperatureLow
    temperatureLowTime
    apparentTemperatureHigh
    apparentTemperatureHighTime
    apparentTemperatureLow
    apparentTemperatureLowTime
    dewPoint
    humidity
    pressure
    windSpeed
    windGust
    windGustTime
    windBearing
    cloudCover
    uvIndex
    uvIndexTime
    visibility
    ozone
    temperatureMin
    temperatureMinTime
    temperatureMax
    temperatureMaxTime
    apparentTemperatureMin
    apparentTemperatureMinTime
    apparentTemperatureMax
    apparentTemperatureMaxTime
  }
  message
}
`;

export const CurrentWeather = `fragment CurrentWeather on CurrentWeather {
  time
  summary
  icon
  nearestStormDistance
  nearestStormBearing
  precipIntensity
  precipProbability
  temperature
  apparentTemperature
  dewPoint
  humidity
  pressure
  windSpeed
  windGust
  windBearing
  cloudCover
  uvIndex
  visibility
  ozone
}
`;

export const Forecast = `fragment Forecast on Forecast {
  time
  summary
  icon
  sunriseTime
  sunsetTime
  moonPhase
  precipIntensity
  precipIntensityMax
  precipIntensityMaxTime
  precipProbability
  precipType
  temperatureHigh
  temperatureHighTime
  temperatureLow
  temperatureLowTime
  apparentTemperatureHigh
  apparentTemperatureHighTime
  apparentTemperatureLow
  apparentTemperatureLowTime
  dewPoint
  humidity
  pressure
  windSpeed
  windGust
  windGustTime
  windBearing
  cloudCover
  uvIndex
  uvIndexTime
  visibility
  ozone
  temperatureMin
  temperatureMinTime
  temperatureMax
  temperatureMaxTime
  apparentTemperatureMin
  apparentTemperatureMinTime
  apparentTemperatureMax
  apparentTemperatureMaxTime
}
`;

export const Subscription = `fragment Subscription on Subscription {
  onData {
    id
    data
  }
}
`;

export const SubscriptionResult = `fragment SubscriptionResult on SubscriptionResult {
  id
  data
}
`;
